cricbit:
  outputs:
    dev:
      dbname: dev_0cny
      host: dpg-ct126kt6l47c73bbdtrg-a.ohio-postgres.render.com
      pass: pvFUn2egsvGqvWEDHn9amVQynkOND4j0
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: patrick
  target: dev
