cricbit:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      port: 5432
      sslmode: "{{ env_var('DBT_SSL_MODE', 'require') }}" # Default to 'require' if not set
