name: Generate Seeds

on:
  push:
    branches:
      - main

jobs:
  generate-seeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run seed generator
        run: python seeds/generate_seed.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update seeds CSV" && git push)
