version: 2

models:
  - name: raw_data
    description: "Raw match data from the source"
    columns:
      - name: match_id
        description: "Unique identifier for each match"
        tests:
          - unique
          - not_null
      - name: match_data
        description: "JSON data containing all match details"
        tests:
          - not_null
      - name: deliveries
        description: "JSON data containing ball-by-ball data"
        tests:
          - not_null

  - name: stg_matches
    description: "Detailed information about each cricket match"
    columns:
      - name: match_id
        description: "Unique identifier for each match"
        tests:
          - unique
          - not_null
        relationships:
          to: ref('raw_data')
          field: match_id
      - name: series_name
        description: "Name of the series or tournament"
      - name: match_num
        description: "Match number within the series"
      - name: match_stage
        description: "Stage of the match (e.g., group, knockout)"
      - name: match_type
        description: "Type of match (e.g., T20, ODI, Test)"
      - name: match_type_num
        description: "Number associated with the match type"
      - name: team_type
        description: "Type of teams playing (e.g., international, club)"
        tests:
          - not_null
          - accepted_values:
              values: ["club", "international"]
      - name: format
        description: "Format of the match"
      - name: season
        description: "Season in which the match was played"
      - name: player_of_match
        description: "Player of the match"
      - name: match_dates
        description: "Dates on which the match was played"
      - name: num_days
        description: "Number of days the match lasted"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
      - name: venue
        description: "Venue where the match was played"
      - name: toss_winner
        description: "Team that won the toss"
      - name: toss_decision
        description: "Decision made by the toss winner (bat/field)"
      - name: outcome
        description: "Outcome of the match"
        tests:
          - accepted_values:
              values: ["win", "draw", "tie", "no result"]
      - name: team1
        description: "First team in the match"
        tests:
          - not_null
      - name: team2
        description: "Second team in the match"
        tests:
          - not_null
      - name: winner
        description: "Team that won the match"
      - name: win_by_wickets
        description: "Number of wickets by which the match was won"
      - name: win_by_runs
        description: "Number of runs by which the match was won"
      - name: win_by_innings
        description: "Number of innings by which the match was won"

  - name: stg_playing_xi
    description: "Information about players in each match's playing XI"
    columns:
      - name: match_id
        description: "Unique identifier for each match"
        tests:
          - not_null
          - relationships:
              to: ref('raw_data')
              field: match_id
      - name: player_id
        description: "Unique identifier for each player"
        tests:
          - not_null
      - name: player_name
        description: "Name of the player"
        tests:
          - not_null
      - name: team_name
        description: "Name of the team the player belongs to"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [match_id, player_id]

  - name: stg_deliveries
    description: "Ball-by-ball data for each match"
    columns:
      - name: match_id
        description: "Unique identifier for each match"
        tests:
          - not_null
          - relationships:
              to: ref('raw_data')
              field: match_id
      - name: inning
        description: "Inning number"
        tests:
          - not_null
      - name: batting_team
        description: "Team batting at the time of the delivery"
        tests:
          - not_null
      - name: over
        description: "Over number"
        tests:
          - not_null
      - name: ball
        description: "Ball number"
        tests:
          - not_null
      - name: batter
        description: "Batter on strike"
        tests:
          - not_null
      - name: bowler
        description: "Bowler who bowled the delivery"
        tests:
          - not_null
      - name: runs_total
        description: "Total runs scored from the delivery"
        tests:
          - not_null
      - name: runs_batter
        description: "Runs scored by the batter"
        tests:
          - not_null
      - name: runs_extras
        description: "Runs scored from extras (byes, wides, etc.)"
        tests:
          - not_null
      - name: non_striker
        description: "Non-striker on the field"
        tests:
          - not_null
      - name: is_wicket
        description: "Whether the delivery resulted in a wicket"
        tests:
          - not_null
      - name: wicket_type
        description: "Type of wicket (if any)"
      - name: player_dismissed
        description: "Player dismissed (if any)"
      - name: fielders
        description: "Fielders involved in the dismissal (if any)"
      - name: wide_runs
        description: "Runs scored from a wide"
        tests:
          - not_null
      - name: bye_runs
        description: "Runs scored from a bye"
        tests:
          - not_null
      - name: legbye_runs
        description: "Runs scored from a legbye"
        tests:
          - not_null
      - name: noball_runs
        description: "Runs scored from a noball"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [match_id, inning, over, ball]

  - name: batting_match_stats
    description: "Batting statistics for each player in an innings"
    columns:
      - name: match_id
        description: "Unique identifier for each match"
        tests:
          - not_null
      - name: player_id
        description: "Unique identifier for each player"
        tests:
          - not_null
      - name: inning
        description: "Inning number"
        tests:
          - not_null
      - name: batter
        description: "Batter name"
        tests:
          - not_null
      - name: runs_scored
        description: "Total runs scored by the player"
        tests:
          - not_null
      - name: balls_faced
        description: "Number of balls faced by the player"
        tests:
          - not_null
      - name: fours
        description: "Number of fours hit by the player"
        tests:
          - not_null
      - name: sixes
        description: "Number of sixes hit by the player"
        tests:
          - not_null
      - name: batting_strike_rate
        description: "Strike rate of the player"
      - name: dismissed
        description: "Whether the player was dismissed"
        tests:
          - not_null
      - name: wicket_type
        description: "How the batter was dismissed (if dismissed)"
        tests:
          - accepted_values:
              values:
                [
                  "bowled",
                  "caught",
                  "lbw",
                  "run out",
                  "stumped",
                  "hit wicket",
                  "not out",
                  "obstructing the field",
                  "retired hurt",
                  "handled the ball",
                  "retired out",
                  "not out",
                ]
      - name: bowler
        description: "Bowler who took the wicket (if applicable)"
      - name: fielders
        description: "Array of fielders involved in dismissal (if applicable)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [match_id, player_id, inning]
      - dbt_utils.expression_is_true:
          expression: "runs_scored >= (fours * 4 + sixes * 6)"
  - name: bowling_match_stats
    description: "Bowling statistics for each player in an innings"
    columns:
      - name: match_id
        description: "Unique identifier for each match"
        tests:
          - not_null
          - relationships:
              to: ref('raw_data')
              field: match_id

      - name: player_id
        description: "Unique identifier for each player"
        tests:
          - not_null
          - relationships:
              to: ref('stg_playing_xi')
              field: player_id

      - name: inning
        description: "Inning number"
        tests:
          - not_null

      - name: bowler
        description: "Bowler name"
        tests:
          - not_null

      - name: runs_conceded
        description: "Total runs conceded by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: balls_bowled
        description: "Number of legal deliveries bowled (excluding wides and no-balls)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: wickets_taken
        description: "Number of wickets taken by the bowler (excluding run-outs and other non-bowler dismissals)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10

      - name: fours_conceded
        description: "Number of boundary fours conceded by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: sixes_conceded
        description: "Number of boundary sixes conceded by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: wide_runs
        description: "Runs conceded by the bowler from wides"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: noball_runs
        description: "Runs conceded by the bowler from no-balls"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: wide_balls
        description: "Number of wides bowled by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: noballs
        description: "Number of no-balls bowled by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: five_wides
        description: "Number of 5wide deliveries bowled by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: dot_balls
        description: "Number of dot balls bowled by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: maidens
        description: "Number of maiden overs bowled by the bowler"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

      - name: economy
        description: "Runs conceded per over (runs_conceded * 6 / balls_bowled)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: bowling_strike_rate
        description: "Average number of balls bowled per wicket taken"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [match_id, player_id, inning]
