version: 2

sources:
  - name: raw
    schema: public
    freshness:
      warn_after: { count: 7, period: day }
      error_after: { count: 10, period: day }
    loaded_at_field: created_at
    tables:
      - name: raw_matches
        description: "Raw data for match information."
        columns:
          - name: match_id
            description: "Unique identifier for the match."
          - name: match_data
            description: "JSONB field containing the match data."
          - name: deliveries
            description: "JSONB field containing the ball-by-ball data."
